# Generated by Django 2.2.1 on 2019-05-14 21:12

from django.db import migrations, models
import django.db.models.deletion
import sovabi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
            ],
            bases=(models.Model, sovabi.models.SovabiModel),
        ),
        migrations.CreateModel(
            name='TypeCelebration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
            ],
            bases=(models.Model, sovabi.models.SovabiModel),
        ),
        migrations.CreateModel(
            name='Messe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messe_date', models.DateTimeField(verbose_name='date of the mass')),
                ('lieu', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='messes', to='messes.Lieu')),
                ('type_celebration', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='messes', to='messes.TypeCelebration')),
            ],
            bases=(models.Model, sovabi.models.SovabiModel),
        ),
    ]
