# Generated by Django 2.2.1 on 2019-05-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lieu',
            options={'verbose_name_plural': 'Lieux'},
        ),
        migrations.AlterModelOptions(
            name='typecelebration',
            options={'verbose_name': 'Type de célébration', 'verbose_name_plural': 'Types de célébration'},
        ),
        migrations.AlterField(
            model_name='messe',
            name='messe_date',
            field=models.DateField(verbose_name='date of the mass'),
        ),
    ]
